markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: "1..2"
  parse_block_html: false
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-relative-links
  - algoliasearch-jekyll

elasticsearch:
  currentversion: 7.1.0
  previousversion: 7.0.1

searchguard:
  esmajorversion: 7
  version: 7.x-35.0.0 
  fullversion: 7.1.0-35.0.0 
  nextminorversion: 7.1.0-35.1.0 
  nextmajorversion: 7.1.0-36.0.0 
  islatestversion: true
  ispreliminaryversion: false
  allversions:
    - 7x-35
    - 6x-25
    - 6x-24
    - 6x-23
    - 6x-22
    - 6x-21
    - 6x-20
    - v5
    - v2

docroots: 
  7x-35: latest
  6x-25: 6.x-25
  6x-24: 6.x-24
  6x-23: 6.x-23
  6x-22: 6.x-22
  6x-21: 6.x-21
  6x-20: 6.x-20
  v5: v5
  v2: v2

index: false

labels:
  navigation:
    quickstart: Quickstart
    first_steps: First steps
    versions: Search Guard Versions
    installation: Installing Search Guard
    upgrading: Upgrading Search Guard
    tls: TLS Setup
    ldap: Active Directory / LDAP
    generating-certificates: "Generating certificates"
    configuration: "Search Guard Configuration"
    authauth: Authentication and Authorization
    rolespermissions: "Users, Roles and Permissions"
    eeadvanced: Advanced Security Features
    dlsfls: Document- and Field-Level Security
    kibana: Kibana
    auditlog: Audit And Compliance Logging
    compliance: Compliance
    restapi: REST API
    elasticstack: Integrating with the Elasticstack
    elasticstack-alternatives: "Elasticstack alternatives"
    kibana-authentication: "Kibana Authentication"
    otherintegrations: Other integrations
    systemintegrators: Advanced system integrator features
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    changelogs-kibana: "Kibana Changelogs"
    changelogs-searchguard: "Search Guard Changelogs"
    changelogs-tlstool: "TLS Tool Changelogs"
    resources: Resources
    7x-35: Search Guard 7.x-35
    6x-25: Search Guard 6.x-25
    6x-24: Search Guard 6.x-24
    6x-23: Search Guard 6.x-23
    6x-22: Search Guard 6.x-22
    6x-21: Search Guard 6.x-21
    6x-20: Search Guard 6.x-20
    v5: Search Guard 5
    v2: Search Guard 2
  collections:
    docs_quickstart: Documentation
    docs_first_steps: First steps
    docs_versions: Documentation
    docs_installation: Documentation
    docs_tls: Documentation
    docs_configuration_changes: Documentation
    docs_auth_auth: Documentation
    docs_roles_permissions: Documentation
    docs_dls_fls: Documentation
    docs_audit_logging: Documentation
    docs_rest_api: Documentation
    docs_kibana: Documentation
    docs_elasticstack: Documentation
    docs_other_integrations: Documentation
    docs_systemintegrators: Documentation
    troubleshooting: Troubleshooting
    changelogs: Changelogs
    resources: Resources

relative_links:
  enabled:     true
  collections: true

domain: https://docs.search-guard.com
baseurl: /latest

collections_dir: _content

collections:
  docs_quickstart:
    output: true
    permalink: :title
  docs_first_steps:
    output: true
    permalink: :title
  docs_versions:
    output: true
    permalink: :title
  docs_installation:
    output: true
    permalink: :title
  docs_tls:
    output: true
    permalink: :title
  docs_configuration_changes:
    output: true
    permalink: :title
  docs_auth_auth:
    output: true
    permalink: :title
  docs_roles_permissions:
    output: true
    permalink: :title
  docs_dls_fls:
    output: true
    permalink: :title
  docs_audit_logging:
    output: true
    permalink: :title
  docs_rest_api:
    output: true
    permalink: :title
  docs_kibana:
    output: true
    permalink: :title
  docs_elasticstack:
    output: true
    permalink: :title
  docs_other_integrations:
    output: true
    permalink: :title
  docs_systemintegrators:
    output: true
    permalink: :title
  troubleshooting:
    output: true
    permalink: :title
  changelogs:
    output: true
    permalink: :title
  resources:
    output: true
    permalink: :title
  common:
    output: true
    permalink: :title

algolia:
  application_id: '2ESDTH812Y'
  index_name:     '6x-20'
  record_css_selector: 'h1, h2, h3, h4, h5'
  allowed_extensions:
    - html
  settings:
    minWordSizefor1Typo: 4
    minWordSizefor2Typos: 8
    hitsPerPage: 20
    maxValuesPerFacet: 100
    version: 2
    attributesToIndex:
      - tags
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - text_all
    attributesToRetrieve: 
      - collection_name
      - text_all
      - unique_hierarchy
      - css_selector
      - url
      - tags
    ignorePlurals: true
    removeStopWords: true
    distinct: true
    attributesForFaceting:
      - category_name
      - h1
    attributesToSnippet: 
      - "text_all:150"
    attributesToHighlight:
      - text
      - text_all
    paginationLimitedTo: 1000
    attributeForDistinct: unique_hierarchy
    exactOnSingleWordQuery: attribute
    disableTypoToleranceOnAttributes:
      - h1
      - h2
      - h3
    ranking: 
      - typo
      - geo
      - words
      - filters
      - proximity
      - attribute
      - exact
      - custom
    customRanking:
      - desc(posted_at)
      - desc(weight.tag_name)
      - asc(weight.position)
    separatorsToIndex: "."
    removeWordsIfNoResults: lastWords
    queryType: prefixLast
    snippetEllipsisText: "..."
    alternativesAsExact: 
      - ignorePlurals
      - singleWordSynonym

eol:
  features:
    - 7.1.0
    - 7.0.1
  updates:
    - 6.8.0

sgversions:
  #esv |sgv |kbv |feat|upd|eol
  search-guard-7:
    - 7.1.1|35.0.0|35.2.0|yes|yes|no
    - 7.1.0|35.0.0|35.2.0|yes|yes|no
    - 7.0.1|35.0.0|35.2.0|yes|yes|no
    - 7.0.0|35.0.0-rc1|35.0.0-rc1|yes|yes|no
    - 7.0.0|35.0.0-beta1|35.0.0-beta1|yes|yes|no
  search-guard-6:
      #esv |sgv |kbv |feat|upd|eol
    - 6.8.0|25.1|18.4|yes|yes|no
    - 6.7.2|25.1|18.4|yes|yes|no
    - 6.7.1|25.1|18.4|no|no|yes
    - 6.7.0|24.3|18.4|no|no|yes
    - 6.6.2|25.1|18.4|yes|yes|no
    - 6.6.1|24.3|18.4|no|no|yes
    - 6.6.0|24.3|18.4|no|no|yes
    - 6.5.4|25.1|18.4|no|yes|no
    - 6.5.3|24.3|18.4|no|no|yes
    - 6.5.2|24.3|18.4|no|no|yes
    - 6.5.1|24.3|18.4|no|no|yes
    - 6.4.3|25.1|17|no|yes|no
    - 6.4.2|24.3|17|no|no|yes
    - 6.4.1|24.3|17|no|no|yes
    - 6.4.0|24.3|17|no|no|yes
    - 6.3.2|24.0|17|no|no|yes
    - 6.3.1|24.0|17|no|no|yes
    - 6.3.0|24.0|17|no|no|yes
    - 6.2.4|23.0|14|no|no|yes
    - 6.2.3|23.0|14|no|no|yes
    - 6.2.2|23.0|14|no|no|yes
    - 6.2.1|23.0|14|no|no|yes
    - 6.1.4|22.3|12|no|no|yes
    - 6.1.3|22.3|12|no|no|yes
    - 6.1.2|22.3|12|no|no|yes
    - 6.1.1|22.3|12|no|no|yes
    - 6.1.0|22.3|12|no|no|yes  